#!/bin/bash

# https://stackoverflow.com/questions/20267910/how-to-add-a-line-in-sed-if-not-match-is-found

name=${1//\//\\/}
value=${2//\//\\/}
sed -i \
	-e '/^#\?\(\s*'"${name}"'\s*=\s*\).*/{s//\1'"${value}"'/;:a;n;ba;q}' \
	-e '$a'"${name}"'='"${value}" $3
