[tool.ruff]
select = [
    "E", 
    "F", 
    "B", 
    "W",
    "Q",
    #"I", # isort
]
#select = ["E4", "E7", "E9", "F", "I"]
ignore = [
    #"B008",  # do not perform function calls in argument defaults
]
fix = false
line-length = 100


[tool.isort]
known-third-party = ["fastapi"]

