[tool.ruff]
fix = false
line-length = 100

[tool.ruff.lint]
select = [
    "E", 
    "F", 
    "B", 
    "W",
    "Q",
    #"I", # isort
]
#select = ["E4", "E7", "E9", "F", "I"]
ignore = [
    #"B008",  # do not perform function calls in argument defaults
    "E262",
    "E265"
]
ignore-init-module-imports = true


[tool.isort]
known-third-party = ["fastapi", "yaml"]

