[tool.ruff]
line-length = 111
fix = false

[tool.ruff.lint]
select = [
    "F",    # Pyflakes (includes undefined variables)
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "Q",    # flake8-quotes (quote style consistency)
    "B",    # flake8-bugbear (likely bugs and design problems)
    "I",    # isort
]
#select = ["E4", "E7", "E9", "F", "I"]
ignore = [
    #"B008",  # do not perform function calls in argument defaults
    "B005", # I like to strip with multi-characters !
    "E731", # I like  lambda assigement
    "E262", # do not work !? 
    "E265", # do not work !?
]
ignore-init-module-imports = true

[tool.ruff.lint.isort]
known-third-party = ["alembic", "tqdm"]
